name: Code Quality Checks
on:
  pull_request:
    branches: ['master', 'develop']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Code Quality Checks
    runs-on: macos-latest
    
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@v4
      
      - name: Install xcpretty
        run: gem install xcpretty
        
      - name: Install Cocoapods
        run: gem install cocoapods
        
      - name: Pod install
        run: pod install --repo-update
        
      - name: Build SDK(iOS)
        run: |
          xcodebuild build -scheme RudderDatabaseEncryption-iOS -workspace RudderDatabaseEncryption.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty
          
      - name: Build SDK(watchOS)
        run: |
          xcodebuild build -scheme RudderDatabaseEncryption-watchOS -workspace RudderDatabaseEncryption.xcworkspace -destination 'platform=watchOS Simulator,name=Apple Watch Series 7 (45mm)' | xcpretty
      
      - name: Build SDK(tvOS)
        run: |
          xcodebuild build -scheme RudderDatabaseEncryption-tvOS -workspace RudderDatabaseEncryption.xcworkspace -destination 'platform=tvOS Simulator,name=Apple TV' | xcpretty
          
      
      - name: Execute pod lint
        run: pod lib lint --no-clean --allow-warnings
